name: Update publications JSON

on:
  schedule:
    - cron: '0 5 1 * *'     # Run monthly on the 1st at 05:00 UTC
  workflow_dispatch: {}      # Allow manual runs from Actions tab

permissions:
  contents: write

concurrency:
  group: publications-json
  cancel-in-progress: true

jobs:
  update-pubs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Fetch publications (writes assets/publications.json)
        run: |
          python scripts/fetch_scholar.py

      - name: Commit & push (rebase if needed)
        env:
          BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

          git add assets/publications.json
          git commit -m "chore: update publications.json [skip ci]"

          for attempt in 1 2 3; do
            if git push origin HEAD:${BRANCH}; then
              echo "✅ Push succeeded."
              exit 0
            fi
            echo "⚠️ Push rejected (attempt $attempt). Rebasing..."
            git fetch origin
            git pull --rebase origin ${BRANCH} || true
            sleep 2
          done

          echo "❌ Failed to push after 3 attempts."
          exit 1
