name: Update publications JSON

on:
  schedule:
    # Runs daily at 05:00 UTC (Cron times are in UTC)
    - cron: "0 5 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-pubs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      # No env/secret needed since the ID is hardcoded in fetch_scholar.py
      - name: Fetch publications
        run: |
          python scripts/fetch_scholar.py

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add assets/publications.json
            git commit -m "chore: update publications.json [skip ci]"
            git push
          else
            echo "No changes."
          fi
